name: BisectHosting-Folia
version: '${version}'
main: com.tcoded.bisecthostingfolia.BisectHostingFolia
api-version: 1.19
folia-supported: true
author: "TechnicallyCoded"
description: "Created by TechnicallyCoded (@TechnicallyCoded#9095) in collaboration with the Havok server (https://discord.gg/dSPTmKmzpu) run by @yomamaeatstoes#6491."
depend:
  - spark
commands:
  bisecthostingstats:
    permission: bisecthostingfolia.command.bisecthostingstats
    alias: [bhs]

permissions:
    bisecthostingfolia.command.bisecthostingstats:
        description: Allows the user to use the /bisecthostingstats command
        default: op