name: BisectHosting-Folia
version: '${version}'
main: com.tcoded.bisecthostingfolia.BisectHostingFolia
api-version: 1.19
folia-supported: true
author: "TechnicallyCoded"
depend:
  - spark
commands:
  bisecthostingstats:
    permission: bisecthostingfolia.command.bisecthostingstats
    alias: [bhs]

permissions:
    bisecthostingfolia.command.bisecthostingstats:
        description: Allows the user to use the /bisecthostingstats command
        default: op